# Generated by Django 5.0.3 on 2024-12-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanage', '0002_rename_ph_data_input_ph_remove_data_ec_data_drain_ec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='drain_ph',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='drain_weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='input_weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='plant_weight',
            field=models.FloatField(),
        ),
    ]
