# Generated by Django 5.0.3 on 2024-12-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanage', '0003_alter_data_drain_ph_alter_data_drain_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
