# Generated by Django 5.0.3 on 2024-12-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanage', '0008_data_drain_ec2_data_drain_ph2_data_drain_weight2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='drain_ec',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='drain_ec2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='input_ec',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='input_ec2',
            field=models.FloatField(),
        ),
    ]
